name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
      - updateURL
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job

    steps:
      - uses: actions/checkout@v3

      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_THANKFUL_STONE_0A8C89A00 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"

          # Your frontend folder
          app_location: "frontend"

          # React build folder
          output_location: "build"